### ISSUE TITLE
Create a new way of auto-updating

### ISSUE THREAD

**Issue by jonkoops** [jonkoops/pirate#43]
Traditionally a release would be tweeted and retrieved using the public API Twitter provided. However this is not possible anymore due to the fact that Twitter has deprecated the public API.

My personal preference would be to use Github for releases going forward ([they have a functionality for this](https://github.com/jonkoops/pirate/releases)). I personally have no time to implement this but it would be nice if someone could pick this up since it is required for the release of a new version.

The API to get new releases from Github can be found here: https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by Ezihp** [comment]
@jonkoops I'll try and see if I can get that fixed some time, although I'm not sure when that will be.

**Comment by Ezihp** [comment]
@jonkoops Will push a release later with this implemented. It was easier than anticipated. :)

**Comment by jonkoops** [comment]
@Ezihp Great! Thanks for all the work you've done. I believe that Github always puts the releases in an archive, so you'll probably need to extract it and move the extracted executable to the app dir.

**Comment by Ezihp** [comment]
@jonkoops Not a problem! Github archives the source only, it seems. Manually added files will stay as is (Pirate.exe). So, what I'm doing now is just tagging the release with the exact version number, eg. "1.0.0.10", the app will look for tag as a version.

Also I am merging the referenced assemblies for convenience, so that the Pirate.exe file alone can be uploaded (and retrieved by the app directly).

Seems to be working great, so I'll push the update shortly.

**Comment by Ezihp** [comment]
@jonkoops Fixed

**Comment by jonkoops** [comment]
@Ezihp Okay. So Pirate.exe will be the only file in the archived release, correct?

**Comment by Ezihp** [comment]
@jonkoops Right. 

`"browser_download_url": "https://github.com/jonkoops/pirate/releases/download/1.0.0.12/Pirate.exe"`

.NET Assemblies can be merged using ILMerge or SmartAssembly.

**Comment by jonkoops** [comment]
Okay. It's looking good to me. If you could go ahead and tag a release v1.0.1.0 I'll whip up a post on the Facebook page saying the issues have been fixed and that people can go ahead and download that version.

**Comment by jonkoops** [comment]
Also, do you want to be mentioned in the blog post? Some contributors prefer to semi-anonymous.

**Comment by Ezihp** [comment]
@jonkoops I already made a release for the auto-update fix, it is v1.0.0.12 (the latest release currently). Clicking on "Downloads" in the readme automatically takes you to latest release.

I would prefer to be semi-anonymous. Github name and/or first name will be fine, if you wish to post. :)

**Comment by Ezihp** [comment]
@jonkoops Sorry about the version number, I just followed what Pirate was using,w hich was 1.0.0.10

**Comment by gaggia78** [comment]
Salve,ho scaricato l'ultima versione la 1.0.0.12 e impostato il mio numero di cellulare come username e ho messo password ma non funziona.Cosa devo fare?
Grazie

**Comment by jonkoops** [comment]
@gaggia78 prega di utilizzare l'indirizzo email associato al tuo account come username. Se il problema persiste, creare una nuova emissione.

Si prega di notare che questo forum è inglese e non italiano. Se non siete in grado di parlare inglese, utilizzare Google Translate o di avere un amico aiutarvi.

> @gaggia78 Please use the email address associated with your account as your username. If the problem persists please create a new issue.

> Please note that this forum is English and not Italian. If you are unable to speak English, use Google Translate or have a friend help you out.

**Comment by gaggia78** [comment]
thanks,
I tried to also enter the email but not work .As new session aims to create a new account by deleting this?

thanks
Diego

**Comment by gaggia78** [comment]
I created a new account and it works.
Thanks for all
Diego
