### ISSUE TITLE
Still i get this error

### ISSUE THREAD

**Issue by LifeBunny** [jonkoops/pirate#47]
![2015-06-25_141234](https://cloud.githubusercontent.com/assets/13048350/8353210/4a47a938-1b44-11e5-8d60-64d563f3e720.jpg)

**Comment by Ezihp** [comment]
I can't reproduce this issue. You may still be running an old version.

**Comment by LifeBunny** [comment]
The version is correct 1.0.0.12 - this morning i just downloaded the app. I inserted the correct user and pass. If i change my password to something else it just doesn't find anything and doesn't show this error.
![2015-06-25_162545](https://cloud.githubusercontent.com/assets/13048350/8355309/31b93162-1b57-11e5-8e06-aa4b520e3548.jpg)

**Comment by rejgert** [comment]
Do you have your ipv6 turned off? I know it doesn't work on my pc when I have that turned on.
Also, your username has to be the phone number you signed up with (in my case at least)

**Comment by jonkoops** [comment]
@LifeBunny Are you absolutely 100% sure your credentials are correct? Have you tried logging into http://vk.com using the same credentials?

**Comment by LifeBunny** [comment]
@rejgert Thanks a lot :) turned ipv6 off and worked well :)

**Comment by jonkoops** [comment]
IPv6 support should probably be added to the app.
