### ISSUE TITLE
Make logging into a VKontakte account manditory

### ISSUE THREAD

**Issue by jonkoops** [jonkoops/pirate#50]
I am seeing a lot of confusion by our because the application gives the illusion that is it possible to use it without logging into your VKontakte account. This because the original application used a set of pre-defined user accounts so users wouldn't need to log into their VKontakte accounts.

I suggest we add a mandatory login in screen that forces users to log into their VKontakte accounts before being able to access the application. Of course it should also be possible to log out of their accounts by pressing a button, this functionality could be added to the settings screen were the users are currently able to edit their credentials.

**Comment by Ezihp** [comment]
After having copied defaults from PirateUX I realised that they all just seemed completely random. My guess is that they none of them ever worked in the first place.

Would it be possible to create a set of default logins? I noticed that vk.com requires mobile verification during account creation.

**Comment by jonkoops** [comment]
I think the default logins are a flawed concept, it makes it easy to block these accounts. I think adding a mandatory login step without any default accounts would solve a lot of issues that are reported. I.e. 90% of the errors people have are related to the fact they didn't enter their credentials or that the credentials are incorrect.

**Comment by Ezihp** [comment]
@jonkoops Do you want to provide some error messages? For now, I'll make it show informative errors when logins fail. No error is shown when default logins fail at the moment. Also, the "invalid login guid" is a bit vague.

**Comment by mrv96** [comment]
Hi, is it possible have this fix also on the UX version? I've tried to decompile UX version, translate the source code because decompiler gives me a C# code, apply the fix and recompile all, but the fix is very difficult to apply because Visual Studio makes a lot of errors when i try to compile a decompiled software

**Comment by jonkoops** [comment]
Yes, lets get rid of the default logins.

**Comment by Ezihp** [comment]
Okay, I've removed default logins and also added more informative errors. Bad login error is now only shown when the the username/password is actually incorrect (assuming the parsing and everything is up to date). If an exception is raised during login, then that is shown instead of just "invalid login".

![Screenshot](http://vgy.me/jsjzCo.png)

**Comment by jonkoops** [comment]
Looks good. But there should probably be a separate login window before the user is able to use the application. And in the settings screen nothing more than a "Logged in as x" label with a "Log out" button.

**Comment by Ezihp** [comment]
@jonkoops Alright. Bottom help labels can go into that window then. It shouldn't let you enter the main window unless they login, right?

**Comment by jonkoops** [comment]
@Ezihp Correct.

**Comment by Ezihp** [comment]
@jonkoops How is this?

![dzvfxo](https://cloud.githubusercontent.com/assets/10199426/8398472/d4705c2e-1def-11e5-85f2-ae4ceb19433a.png)

![facvwg](https://cloud.githubusercontent.com/assets/10199426/8398479/0137c30a-1df0-11e5-99ea-5dc90e179ab8.png)

It is functional now. It only saves your credentials on successful logins now as well, so if you happened to log out via settings without logging back in, the searcher will attempt to login with previously saved credentials.

**Comment by Ezihp** [comment]
Let me know of a version number you'd prefer for this release.

**Comment by jonkoops** [comment]
@Ezihp Excellent. Seems good to me, I'd recommend to just tag it 1.0.0.13.

**Comment by jonkoops** [comment]
Nice work. Thanks again for your hard work @Ezihp!

**Comment by Ezihp** [comment]
@jonkoops Released. Feel free to edit the readme however you want it. :stuck_out_tongue:

**Comment by jonkoops** [comment]
@Ezihp The application seems to be freezing when attempting to log in (works afterwards). Are you using a Thread?

**Comment by Ezihp** [comment]
@jonkoops Logging in is done from the same thread. I felt that it would suffice, considering that you now login in advance. If it should be done from a seperate thread, than the GUI needs to be synchronized with that, so users can't login while it is in progress.

**Comment by jonkoops** [comment]
Adding a boolean to disable the UI should be enough.
