### ISSUE TITLE
Login update for UX version

### ISSUE THREAD

**Issue by mrv96** [jonkoops/pirate#51]
Hi, is it possible have this fix also on the UX version? I've tried to decompile UX version, translate the source code because decompiler gives me a C# code, apply the fix and recompile all, but the fix is very difficult to apply because Visual Studio makes a lot of errors when i try to compile a decompiled software

**Comment by jonkoops** [comment]
We do not have the UX source code so we unfortunately cannot fix this,

**Comment by mrv96** [comment]
If you want i can give you a Visual Studio project with a decompiled vb.net code of UX version. I've seen few errors in the form design, but the main code should works. Maybe it will be simple for an expert programmer rebuild the code and fix it. UX version is very useful.

**Comment by jonkoops** [comment]
If you wish to add functionality that was previously in the UX version please submit a pull request.
