### ISSUE TITLE
my pirate is still not working

### ISSUE THREAD

**Issue by Joa297** [jonkoops/pirate#53]
Hi there my pirate is still not working after i sign up on VK. I recently moved from holland to Aruba is this a problem? Can i use pirate here on Aruba?

pls let me know, thank you in advanced. 

Kind Regards

**Comment by jonkoops** [comment]
Please give a description of the error you are encountering and possibly a screenshot of the issue. We can't work on a bug report if it is lacking details.

**Comment by Joa297** [comment]
Goodafternoon,
 
Thank you very much for your fast reply, really apreciate is.
 
Unfortunatly i dont get any errors the only thing i get is a white screen. When i try to type in name of artist ore track id it doenst show anything. See picture in attachment.  Kind regards, Joalina
 
Date: Mon, 29 Jun 2015 03:48:02 -0700

**Comment by jonkoops** [comment]
@Joa297 You'll have to post that attachment on GitHub it's not showing up. Have you tried using the latest version (please share your version number)?

**Comment by Joa297** [comment]
![20150629_151116](https://cloud.githubusercontent.com/assets/13096617/8424909/a37c8ab8-1f00-11e5-8eb7-fbfc3d92a575.jpg)
This is what i get. Now i;m trying to find Pirate on my comp but al of the sudden its gone.

**Comment by jonkoops** [comment]
@Joa297 Could you go ahead and make sure you are running the lastest version by downloading it [here](https://github.com/jonkoops/pirate/releases/download/1.0.0.13/Pirate.exe)?

**Comment by Joa297** [comment]
i did but. But i still get the same thing. see foto:

![20150630_141852](https://cloud.githubusercontent.com/assets/13096617/8443043/6bf8f486-1f83-11e5-8264-2ae1057d88dd.jpg)
![20150630_141846](https://cloud.githubusercontent.com/assets/13096617/8443042/6b978480-1f83-11e5-8db8-88da2d92f5bf.jpg)

**Comment by jonkoops** [comment]
Did you sign in using your telepone number or is that actually your username?

**Comment by Joa297** [comment]
I signed in wit my telefoonnummer. I moved recently from the Netherlands to Aruba so i changed my number. Is that a problem?

**Comment by Joa297** [comment]
I just found out what the problem was. I didnt totally complete my profile on VK now i just did and guess what its running... pffff mannnn i am so happy You have NO idea.... Thank you very much for all the support and quick responses. Keep on all the good work!!! You guys are awesome!!!! Greetz Joa

**Comment by Joa297** [comment]
One more question tho, is it true that you cannot listen to the track anymore before downloading?

**Comment by jonkoops** [comment]
Yes, this feature was in the UX version of which we do no longer have the source code of. The current version is based on the original app which doesn't have the preview functionality.

Since your issue has been resolved I'll go ahead and close it.

**Comment by Joa297** [comment]
Yes, once again Thank you!
 
Kind Regards
 
Date: Mon, 6 Jul 2015 00:37:33 -0700
