### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by MelvinFR** [jonkoops/pirate#54]
Hi,

If I want to login with the newest version of pirate it says that the password/username is incorrect. But I can login to vkontakte with the same credentials. 
![49be8e5e9b99f5eb6d225ee93e7528f0](https://cloud.githubusercontent.com/assets/13245380/8584280/4fa9e170-25d5-11e5-8192-1d2e22864989.png)

With an older version of Pirate I still get the same error, even with the same credentials as I used before this error. 
![c358ced44af854bd7ab378ed7887645e](https://cloud.githubusercontent.com/assets/13245380/8584316/87cce71e-25d5-11e5-8a01-f821aaf36d67.png)

I hope this problem can get fixed.

Thanks in advance!

Greetz

**Comment by jonkoops** [comment]
Logging in is working fine for other folks so it is probably an issue with your account specifically. Please make sure you are able to log in on the [VKontakte website](http://vk.com/) and that you have completed the setup of your account.

Someone was having [similar issues](53) and fixed them this way.

**Comment by Ezihp** [comment]
If you have mistyped username/password several times, vk.com starts requiring captcha, which renders the app unable to login for the duration (possibly hours).

**Comment by jonkoops** [comment]
@MelvinFR Are you still experiencing this issue?

**Comment by jonkoops** [comment]
I am going ahead and close this issue. If you are still experiencing issues I will reopen it.
