### ISSUE TITLE
Credentials are not working with new update login

### ISSUE THREAD

**Issue by allfourelements** [jonkoops/pirate#55]
I've now created two vk.com logins and I cannot get either of them to work. They are giving me the "username or password is incorrect. Please try again" error. Both of these logins are verified on vk.com and are fully setup. I've setup the email address on both accounts and I have tried to use the phone number for the credentials which still doesn't work with ThePirateApp. Is there any fix for this. I've tried looking at other issues and they seem to have the same problem, but not the right solution for me.

**Comment by jonkoops** [comment]
@allfourelements Please try to disable IPv6 and see if the problem persists.

**Comment by allfourelements** [comment]
Resolved, thank you. What will disabling IPv6 do though?

**Comment by jonkoops** [comment]
https://youtu.be/aor29pGhlFE
