### ISSUE TITLE
save dialog

### ISSUE THREAD

**Issue by pipiscrew** [jonkoops/pirate#59]
when at common dialog, enter a filename and press save (versus click save button) a new common dialog fired again..

**Comment by jonkoops** [comment]
You can configure this in the settings of the application. Open the settings by clicking the wrench icon located next to the 'Search' button. Under the first tab titled 'Downloads' press the 'Browse...' button to select a location where you want to save your downloads by default. After you close the settings dialog your settings should be saved. When downloading a file it should now use the directory you provided, and you should still be able to choose a different file name.

I hope this resolves your issue.
