### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Daan00** [jonkoops/pirate#60]
Hello,

I can't login anymore. I had updated de programme and wanted to log in, but it said that my password and username were incorrect. But my password and username are correct, because I can login by vk, Can you help me?

**Comment by jonkoops** [comment]
Did you sign in using your email address as your username?

**Comment by Daan00** [comment]
No I did sign in using my mobile phone number. But later I have linked my email adress.

**Comment by jonkoops** [comment]
Use your email address as your username when signing in.

**Comment by Daan00** [comment]
It doesn't work?

**Comment by jonkoops** [comment]
It's probably IPv6 causing the issue. Try disbabling it.
