### ISSUE TITLE
user authentication failed

### ISSUE THREAD

**Issue by CheckaWiemi** [jonkoops/pirate#62]
Hi,

I got a huge problem. A friend of mine just bought a new PC and installed the latest version of pirate (1.0.0.13) and enters his account and it always says "The username or password is incorrect. Please try again". So I try again and again and it's always the same. I've also tried my account and it says the same  "The username or password is incorrect. Please try again".

I've tried his account on one of my PCs and it works fine. So why does this message appear again and again?

**Comment by jonkoops** [comment]
Please try the following:
- Log in with your **email address** as your username (please make sure that the credentials are correct by logging into [VKontakte](https://vk.com/)).
- Disable IPv6 on your computer, this is related to issue #57.

**Comment by CheckaWiemi** [comment]
The problem was really IPv6. After deactivating IPv6 it worked great. Thanks a lot!
