### ISSUE TITLE
Pirate XP is not working

### ISSUE THREAD

**Issue by Joa297** [jonkoops/pirate#67]
![pirate issue](https://cloud.githubusercontent.com/assets/13096617/21414342/dc298d18-c7fe-11e6-9a05-f39c1e74905e.jpg)

Pirate is not working. See attachtment for issue.

**Comment by vever001** [comment]
What a bummer: https://vk.com/dev/audio_api
Apparently VK shut down all the methods related to Audio. So I suppose all the following methods: https://vk.com/dev/audio
Pirate is using the audio.search method: https://vk.com/dev/audio.search

We could possibly use the old way (prior to VkNET) which is to simulate how browsers are searching for songs. So make requests to https://vk.com/al_audio.php

**Comment by Joa297** [comment]
Hello,

Thank you very much for your reply but I don't understand what you mean with make request to...

And what was the old way prior to vknet? Please help me out, thank you in advanced.

**Comment by jonkoops** [comment]
#68 resolves this issue, we'll try to get a new build out soon.

**Comment by wimpyrbx** [comment]
any news on the potential new build?

**Comment by jonkoops** [comment]
@wimpyrbx At the moment the before mentioned pull request has not resolved the issue. I am still waiting for a response from the author of the pull request.

**Comment by vever001** [comment]
Hello,

Sry for the late reply.
@jonkoops I created a PR to update the assembly version to 1.0.0.15: #69 
Here's a build I just did which includes the PR: https://drive.google.com/open?id=0Bw8a04KSBsQtQnF5WTE0Q2RrSTA

**Comment by black2279** [comment]
Hello,
I saw that the last build on master doesn't working properly.
I think it's a regular expression problem.

I tried with this fix and it seems to be working:
[https://github.com/black2279/pirate/commit/59387d873c4b18f12dfe27794e961b80d2611a9f](https://github.com/black2279/pirate/commit/59387d873c4b18f12dfe27794e961b80d2611a9f)

**Comment by jonkoops** [comment]
@vever001 Yeah, I am able to make a build on my local machine and bumping the version is not a problem. Let me try to apply @black2279's fix and see if that resolves the problem.

**Comment by Joa297** [comment]
Hello,

So what's the latest update is it back on? Thank you for your reply.
________________________________
Van: Cristian Andrighetto <notifications@github.com>
Verzonden: donderdag 16 februari 2017 02:02:43
Aan: jonkoops/pirate
CC: Joa297; Author
Onderwerp: Re: [jonkoops/pirate] Pirate XP is not working (#67)


Hello,
I saw that the last build on master doesn't working properly.
I think it's a regular expression problem.

I tried with this fix and it seems to be working:
black2279@59387d8<https://github.com/black2279/pirate/commit/59387d873c4b18f12dfe27794e961b80d2611a9f>

**Comment by wimpyrbx** [comment]
the build https://drive.google.com/file/d/0Bw8a04KSBsQtQnF5WTE0Q2RrSTA/view works for login and searching/downloading, but not displaying kbps and length. still, an improvement from not working so thanks :)

**Comment by wimpyrbx** [comment]
nevermind. it only downloads an advertisement mp3.

**Comment by black2279** [comment]
Hello,  
I have some news. Vk.com removes public_access to API but in the ads link encode the song links.
I check client scripts on vk.com and I found the way to decode them.
I wrote a script that does the work. 
This is only a standalone test but we have to find the way to porting these functions in Pirate.

Link for the script:  [https://drive.google.com/file/d/0BxkFbaXDmkFmTnJhaWRIZzlfbE0/view?usp=sharing](https://drive.google.com/file/d/0BxkFbaXDmkFmTnJhaWRIZzlfbE0/view?usp=sharing)

**Comment by black2279** [comment]
Hello guys,
I have a new temporary build. This new build uses javascript functions present in the script in the comment above.
Check if it works for you.
https://drive.google.com/file/d/0BxkFbaXDmkFmVE10TlBtendKeUE/view?usp=sharing

PS: I have to embed .js in the app

**Comment by jonkoops** [comment]
I'll try to make a build tonight and see if the problem has been fixed. But since VKontakte is cracking down on us I think keeping this project alive is only going to get more difficult. Especially since I am pretty busy with day to day life and not even active in the area this project is (Windows development, VB.NET, etc).

I guess we'll have to see how far we can go before this runs to an end.

**Comment by jonkoops** [comment]
So I've been looking around and all of the audio fragments have been replaced with some kind of ad from VKontakte. I do no longer maintain this so I have no intention of messing around and fixing the problem. This is just going to turn into a cat and mouse game I don't feel like playing.

Hence I am closing this project - if anyone wishes to take ownership please let me know in this thread.

**Comment by vegeta2401** [comment]
Please continue to develop this project. 
It's very important for me and i'm grateful to you as far as it is done to it.
Please continue!!!

**Comment by vegeta2401** [comment]
@jonkoops @black2279 Please continue :-)

**Comment by jonkoops** [comment]
@vegeta2401 I will not continue development of this project. I am open to anyone who would like to take ownership though.

**Comment by vegeta2401** [comment]
I'd like to help you,but i'm not a developer.
Please continue :-)

**Comment by vever001** [comment]
I can suggest the [MusicSig chrome extension](https://chrome.google.com/webstore/detail/musicsig-%D0%B4%D0%BB%D1%8F-%D0%B2%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%B5-vk/hanjiajgnonaobdlklncdjdmpbomlhoa/related?hl=en) as an alternative. You get the bitrate, search autocomplete, download option, filters, direct playback and the original vk interface.

**Comment by black2279** [comment]
@jonkoops If you want I can take the ownership but I don't know how much the future development will last.
